seed: 22

architecture:
  name: "pet"
  training:
    finetune:
      method: "heads"
      read_from: "../pet-mad-v1.0.2.ckpt"
      config:
        head_modules: ['node_heads', 'edge_heads']
        last_layer_modules: ['node_last_layers', 'edge_last_layers']
    learning_rate: 1e-5
    num_epochs: 1000
    checkpoint_interval: 10
    num_epochs_warmup: 5


# training set section
training_set:
  systems: 
    read_from: "../train.extxyz"
    length_unit: angstrom
  targets:
    mtt::LPS:
      quantity: "energy"
      key: "energy"
      unit: "eV" # very important to run simulations
      forces:
        key: "forces"

validation_set:
  systems: 
    read_from: "../val.extxyz"
    length_unit: angstrom
  targets:
    mtt::LPS:
      quantity: "energy"
      key: "energy"
      unit: "eV" # very important to run simulations
      forces:
        key: "forces"


test_set:
  systems: 
    read_from: "../test.extxyz"
    length_unit: angstrom
  targets:
    mtt::LPS:
      quantity: "energy"
      key: "energy"
      unit: "eV" # very important to run simulationsA
      forces:
        key: "forces"

