seed: 22

architecture:
  name: "pet"
  training:
    finetune:
      method: "full" # This stands for the full fine-tuning
      read_from: "../pet-mad-v1.0.2.ckpt"
    learning_rate: 1e-5
    num_epochs: 50


# training set section
training_set:
  systems: 
    read_from: "../train.extxyz"
    length_unit: angstrom
  targets:
    energy:
      key: "energy"
      unit: "eV" # very important to run simulations
      forces:
        key: "force"

validation_set:
  systems: 
    read_from: "../val.xyz"
    length_unit: angstrom
  targets:
    energy:
      key: "energy"
      unit: "eV" # very important to run simulations
      forces:
        key: "force"


test_set:
  systems: 
    read_from: "../test.xyz"
    length_unit: angstrom
  targets:
    energy:
      key: "energy"
      unit: "eV" # very important to run simulationsA
      forces:
        key: "force"
